criticality_score/run.py

Based on feedback from Georgios Gousios

Fix reset time from github api instead of one hour.

---

criticality_score/generate.py

Fixes https://github.com/ossf/criticality_score/issues/33

Workaround for using arbitrary sample size, beyond 1000 github results.

---

criticality_score/generate.py
criticality_score/run.py

Fixes https://github.com/ossf/criticality_score/issues/14
Also add Kotlin and Scala to java language list. Fixes
https://github.com/ossf/criticality_score/issues/50

Fix project age calculation to incorporate first commit date.

---

criticality_score/generate.py

Tiny fix for C# language:
https://en.wikipedia.org/wiki/C_Sharp_(programming_language)

Rename chash to csharp

---

popularity_correlation.md

The `popularity_correlation.md` file being contributed in this pull request is a description of the methodology used to evaluate the correlation between the criticality score of a project and the popularity of the project. See https://groups.google.com/g/wg-securing-critical-projects/c/wi09IkuTfIU for the discussion that led to this contribution.

Correlation between Criticality Score and Popularity

---

criticality_score/generate.py
criticality_score/run.py

Would you like to fix these four tiny pylint messages?

Fix pylint messages

---

criticality_score/generate.py
criticality_score/run.py

Also, fix a hang bug when dependents count returns zero result.

Support generation via github orgs.

---

criticality_score/generate.py

This commit adds support for popular R projects list generation

add support for R language

---

docs/design/milestone_1.md
docs/glossary.md

This doc describes work towards solving issue #108

Add a milestone 1 doc.

---

cmd/enumerate_github/main.go
internal/workerpool/workerpool.go
internal/workerpool/workerpool_test.go

Currently used only with the enumerate_github command, but upcoming PR will add support to the collect_signals command.

Add a smaller helper library for initing a pool of workers.

---

cmd/collect_signals/result/csv.go

Also improve the error reporting so it is easy to figure out what went wrong.

Fix a bug where nil values weren't being marshal'd correctly.

---

cmd/collect_signals/github/collector.go
cmd/collect_signals/github/legacy/constants.go
cmd/collect_signals/github/legacy/issues.go
internal/githubapi/roundtripper.go

https://github.com/ceph/ceph has a lot of issues and was causing breakage while grabbing the issue counts.

Handle the case where GitHub returns 5xx when there are lots of issues

---

cmd/collect_signals/depsdev/collector.go
cmd/collect_signals/depsdev/dependents.go
cmd/collect_signals/main.go

- gcp project id is autodetected now.
- deps.dev requires explicit disabling to improve usability.
- deps.dev dataset name can be set from the command line.

Improve deps.dev support with new flags and GCP project autodetect

---

cmd/enumerate_github/README.md
cmd/scorer/algorithm/distribution.go
cmd/scorer/algorithm/value.go
cmd/scorer/main.go
config/scorer/original_pike.yml
config/scorer/pike_depsdev.yml

1. "zapfian" should actually be "zipfian"
2. Some minor README tweak to a headings
3. Tweak the help text for the scorer's -config flag to indicate that it is required.
4. Clean up some extraneous comments

Fix a bunch of minor issues.

---

internal/outfile/outfile.go

This allows the usage of mimio as s3 storage.

Allow options to be present in the URL query string.

---

infra/k8s/enumerate_github.yaml

Fix the broken GCS link, extend the memory limits.

---

go.mod
infra/k8s/enumerate_github.yaml

Lower  min stars for k8s to 50

---

internal/log/config.go
internal/log/env.go

Woops. Forgot to add new log helper code.

---

.github/workflows/ci.yml

Add a GitHub workflow that runs tests and linter.

---

.github/workflows/ci.yml

super-linter has trouble with Golang :(

Switch to golangci-lint-action instead of super-linter

---

cmd/scorer/main.go
go.mod
internal/textvarflag/flag_test.go

Remove last of logrus usage

---

CONTRIBUTING.md

Update CONTRIBUTING guide to point to Go code.

---

SECURITY.md

Add a SECURITY.md file.

---

cmd/collect_signals/Dockerfile

Make collect_signals Dockerfile work without buildkit

---

infra/config.yaml
infra/k8s/auth.yaml
infra/k8s/controller.yaml
infra/k8s/transfer.yaml
infra/k8s/worker.yaml

Initial commit of production kubernetes configs for each service needed to run criticality score in production.

Initial version of kubernetes configs for each service.

---

cmd/criticality_score/Dockerfile

Fix the chmod in the criticality_score Dockerfile.

---

infra/clouddeploy.yaml

Fix more Google Cloud name violations.

---

.github/dependabot.yml

Add /tools to dependabot config

---

go.mod
go.sum
go.work.sum

- Fixed issue https://deps.dev/advisory/osv/GO-2022-1144
https://deps.dev/go/github.com%2Fossf%2Fcriticality_score

Fixed issue GO-2022-1144

---

.github/workflows/codeql-analysis.yml

- Updated codeql to include Golang

Updated codeql to Include Golang

---

README.md

#288
Signed-off-by: Brandon Simmons <brandon.m.simmons@gmail.com>

Provide working installation instructions

---

internal/scorer/algorithm/wam/wam.go

- Refacted `Score()` in `wam.go` to make it cleaner

Refactored Score in wam.go

---

infra/envs/base/worker.yaml
infra/k8s/enumerate_github.yaml
internal/githubapi/roundtripper.go
internal/githubapi/roundtripper_test.go

- set the worker replicas to match the current prod value
- increase the min stars to lower the number of repos to under 500k
- add urls to logs output by the GH error handling code

Tweaks for the production restart.

---

infra/k8s/enumerate_github.yaml

Brings the number of repos in enumeration to just under 400k

Increase the number of stars for the enumeration to reduce the number of repos.

---

internal/collector/github/legacy/constants.go

Fix the issue lookback duration to be 90 days.
