ossf/criticality_score

- criticality_score/generate.py
I wanted to try whether I could make language parameter optional, so it can just list all the repos.
I didn't try it with a large sample size but it looks like it's doing the job now.
So, I wanted to share it but feel free to discard it (or make necessary changes) of course.
> Make language parameter optional

- setup.py
The criticality_score is using some high version feature, such as `print(f'')` Formatted string literals[1], which is added in pyhton 3.6.
That means the script would be break down in the python version < 3.6.
This patch bump the python_requires to 3.6 to make sure the script works well.
[1] https://docs.python.org/3.6/reference/lexical_analysis.html#formatted-string-literals
> Bump python_requires to 3.6

- criticality_score/generate.py
When we run generate script for large number of repos, it becomes difficult to follow the exceptions.
Not sure what are the best practices but I added basic logging by following this example. Looks like it's doing the job:
https://stackoverflow.com/questions/15474095/writing-a-log-file-from-python-program
As usual, feel free to accept/discard it
> Add logging to generate script

- criticality_score/generate.py
When running generate script with large numbers, there's no way of knowing how many repos are processed and how many left to go. So, I wanted to display an index for each line. Since I started playing with it, I changed the output format a little.
**Current output**
```shell
name,url,language,created_since,updated_since,contributor_count,org_count,commit_frequency,recent_releases_count,updated_issues_count,closed_issues_count,comment_frequency,dependents_count,criticality_score
Hacky,https://github.com/eliaskg/Hacky,Objective-C,97,84,4,2,0.0,0,0,0,0,0,0.10185
flame.js,https://github.com/flamejs/flame.js,JavaScript,107,57,34,5,0.0,0,0,0,0,2,0.22108
```
**New output**: no header, each line only shows index, name, url, score
```shell
0 - iglo - https://github.com/subosito/iglo - 0.1077
1 - …
```
> Update format of generate script console output

- criticality_score/run.py
Due to the negative weight, the numerator of score may be greater than the denominator, that means the score would be greater than 1. And the numerator may be also less than 0, that means final score would be less than 0.
So in this patch, we set the finall criticality_score between 0 (least-critical) and 1 (most-critical).
Close: https://github.com/ossf/criticality_score/issues/68
> Make sure criticality_score between 0 and 1

- .gitignore
I'm using Visual Studio Code to edit the project.
At some point, it created this ".ropeproject" folder, and apparently it can be ignored:
https://github.com/github/gitignore/blob/master/Python.gitignore
> Add .ropeproject folder to gitignore

- criticality_score/generate.py
- criticality_score/run.py
I realized that it's possible to use multiple auth tokens for GitHub, which is a life-saver. Thanks for that ✌
Now generate script takes much less time to run.
While I was using multiple tokens, I noticed that `get_github_auth_token` function doesn't take the shortest wait time but just uses the wait time of the last token. Although not sure how much this would improve the process but I wanted to try refactoring it.
Here is the summary of this update:
- Introduced `_CACHED_GITHUB_TOKENS` global variable that stores `token`, `token_obj` and `reset` data as a list
- `get_github_auth_token` returns an object from this list
- While searching for the next active token, it ignores the already expired tokens
- If all tokens are expired, it finds the minimum wait time and goes to sleep
- That …
> Refactor get_github_auth_token

- criticality_score/generate.py
- criticality_score/run.py
I was looking into whether we can improve handling "deleted/non-existing repos" cases:
* It shows a "Repo not found" message, instead of the exception
* In "generate" script, if the repo is not found, it doesn't continue with the retries
Current output for GitHub in "not found" case:
```shell
Traceback (most recent call last):
File "..\Python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "..\Python39\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "..\criticality_score\criticality_score\run.py", line 584, in <module>
main()
File "..\criticality_score\criticality_score\run.py", line 564, in main
repo = get_repository(args.repo)
File "..\criticality_score\criticality_score\run.py", line 526, in get_repository
repo = …
```
> Handle not found cases

- criticality_score/run.py
I tried to add "logger" to run script before but somehow I couldn't make it work. Now it turned out to be a very simple one 🤷‍♂️
I'm just not sure about moving "initialize_logging_handlers" function to a generic place.
It's very similar to the one in "generate" script:
**run**
```python
def initialize_logging_handlers():
logging.basicConfig(level=logging.INFO)
logging.getLogger('').handlers.clear()
console = logging.StreamHandler()
console.setLevel(logging.INFO)
logging.getLogger('').addHandler(console)
```
**generate**
```python
def initialize_logging_handlers(output_dir):
log_filename = os.path.join(output_dir, 'output.log')
logging.basicConfig(filename=log_filename, filemode='w', level=logging.INFO)
console = logging.StreamHandler()
console.setLevel(logging.INFO) …
```
> Add logger to run script

- criticality_score/run.py
When we do search on related commits of specific repo_name in github, we
perhaps get 200 status_code but no right page result, then get an
unexpected 0 result accidently.
This patch breaks retry loop only when result is 200 status with match
result rather than only 200 status.
> Add page query retries when no match

- criticality_score/constants.py
Current regex doesn't cover '1 commit result' case, that means if we
get only 1 commit result, the dependent number will be set to 0.
This patch try to fix it by use '* commit result' to match 'n commit results'
and '1 commit result' case.
> Fix regex to cover '1 commit result' case

- criticality_score/generate.py
- criticality_score/run.py
When I was running the script, I bumped into these repos that they fall into the filter due to high number of stars but they're actually empty and the script throws an exception:
https://github.com/fossasia/libregraphics.asia
https://github.com/libredesktop/libredesktop-events
https://github.com/libredesktop/libredesktop-project-list
https://github.com/libredesktop/LibreDesktop-Specs
https://github.com/meilix/arch-meilix
https://github.com/meilix/deb-meilix
https://github.com/meilix/meilix-addons
https://github.com/meilix/meilix-art
https://github.com/meilix/meilix-connect
https://github.com/meilix/meilix-web
https://github.com/susiai/susi_partners
https://github.com/susiai/susi_sdk
https://github.com/ascoders/blog
https://github.com/bigdongdongCLUB/newGCP …
> Handle empty repo case

- criticality_score/run.py
When we request `get_tags` for this repo, GitHub API throws an exception (interestingly, this was the only repo that was persistent in throwing an exception):
https://github.com/hortonworks/cloudbreak
```shell
python -u -m criticality_score.run --repo github.com/hortonworks/cloudbreak
```
It has 8,707 tags, so probably that's a large number for the API to process.
The only detail is that in catch block of "contributors", you return "10" as a default value. Should I set a similar default value for tags as well?
> Handle get_tags exception

- README.md
- criticality_score/run.py
I wanted to submit a suggestion to include GitHub Watchers (to help assess popularity) and the GitHub Description (to clarify the project's overall goal). I am currently helping contribute to OSSF's Security Metrics project, in which we are retrieving several of the GitHub metrics covered in this project (but also need to analyze the two mentioned above to help with our overall security assessment). If these can be included via the pull request I have submitted that would be extremely helpful. Thank you!
> Add Watchers/Description Metrics

- README.md
- criticality_score/defaults.py
- criticality_score/run.py
Adds a command line parameter to override the weight and threshold
of the build-in parameters.
This addresses Issue #104 
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
> Allow overriding default parameters

- cmd/enumerate_github/githubsearch/repos.go
- cmd/enumerate_github/pagination/pagination.go
This better handles the case where another page is left, but
contains no nodes and makes it less ambiguous.
> Remove "Finished()" API in favor of the io.EOF error.

- cmd/collect_signals/github/collector.go
The Python code handles this situation by setting releases to 0
> Fix a div by zero bug when daysSinceCreated == 0, and there are tags.

- cmd/collect_signals/projectrepo/resolver.go
This is particularly useful because we can use the global resolver to avoid passing instances of the ghRepoFactory around.
> Adds a Resolver for turning a url into a Repo.

- internal/retry/request.go
- internal/retry/request_test.go
A following PR will use this library to handle retries for the GitHub API.
This library is written this way to facilitate testing, which I thought
was particularly important for retry related logic as it is hard to
cover all the various cases during manual testing.
> Add a library to handle the retry logic.

- cmd/collect_signals/main.go
- internal/githubapi/roundtripper.go
- internal/githubapi/roundtripper_test.go
1. Adds a RetryAfter function for processing responses with `Retry-After` header (will move to the retry library in the future)
2. Adds a SecondaryRateLimit function for detecting rate limiting from GitHub and pausing immediately
3. Adds a ServerError400 function for detecting odd server errors from GitHub
4. Adds a ServerError function for detecting any 5xx server error and retrying (except for `issues/comments` which knowingly fails on lots for large numbers of comments).
All of these are well tested to ensure the retry behavior works correctly.
> Add retry logic for github errors to improve reliability.

- infra/k8s/enumerate_github.yaml
Currently, only runs for repos >= 100 stars, for 2021.
It is triggered each day at 23:00 UTC or 9am AEST.
Prior to running it needs the bucket to be created with access for the correct service account.
> Add an initial k8s config for running the enumerate_github tool.

- cmd/enumerate_github/main.go
- cmd/enumerate_github/repowriter/scorecard.go
- cmd/enumerate_github/repowriter/scorecard_test.go
- cmd/enumerate_github/repowriter/text.go
- cmd/enumerate_github/repowriter/text_test.go
- cmd/enumerate_github/repowriter/type.go
- cmd/enumerate_github/repowriter/type_test.go
- cmd/enumerate_github/repowriter/writer.go
- go.mod
- go.sum
- go.work.sum
To simplify productionizing, add support for returning enumerated repository urls in Scorecard's csv format.
This doesn't directly import `RepoFormat` from scorecard because:
- it is in an "internal" directory
- uses the unmaintained csvutil project to generate the header row
> Add support for output enumerated urls in a scorecard compatible format.

- cmd/collect_signals/depsdev/collector.go
- cmd/collect_signals/depsdev/dependents.go
- cmd/collect_signals/github/factory.go
- cmd/collect_signals/github/repo.go
- cmd/collect_signals/main.go
- internal/githubapi/roundtripper.go
- internal/githubapi/roundtripper_test.go
Zap is much better at production logging. This change helps prepare signal collection for productionization.
> Migrate the collect_signals tool over to zap for logging.

- infra/k8s/enumerate_github.yaml
The GitHub enumeration has been running in prod for a while.
This change is the production configuration.
Twice weekly, >=20 stars, all time.
> Complete the GitHub enumeration roll-out.

- cmd/collect_signals/main.go
- cmd/criticality_score/README.md
- cmd/criticality_score/main.go
- cmd/enumerate_github/README.md
- cmd/enumerate_github/main.go
- cmd/scorer/README.md
- cmd/scorer/main.go
- go.work.sum
- infra/k8s/enumerate_github.yaml
- infra/test/docker-compose.yml
- internal/outfile/outfile.go
- internal/outfile/outfile_test.go
Use -out=file to specify the output file, rather than as a positional arg.
This change is important for simplifying the CLI for `criticality_score`, so it was applied across all the commands.
The following changes were made to support this:
- A flag was added to outfile for the filename
- The capability to transform filenames was added to outfile (to support run-ids in enumeration)
- All the READMEs were updated.
This changes moves us closer to deprecating the Python version
> Make the output file an explicit flag, rather than a positional arg

- infra/cloudbuild/collect_signals/cloudbuild.yaml
This automatically builds the collect_signals image we need to run criticality score in production.
> Add a cloudbuild.yaml for collect_signals worker.

- cmd/collect_signals/main.go
- cmd/collect_signals/worker.go
- cmd/criticality_score/main.go
- internal/collector/signal/signal.go
- internal/signalio/csv.go
- internal/signalio/json.go
- internal/signalio/type.go
- internal/signalio/type_test.go
The Scorecard transfer expects to see JSON to import.
I was planning to add this anyway, but the BQ load just expidited this.
All values are aggregated into objects based on their namespace.
> Add JSON support for outputting signals.

- cmd/criticality_score/README.md
- cmd/criticality_score/main.go
- internal/signalio/csv.go
- internal/signalio/helpers.go
- internal/signalio/text.go
- internal/signalio/type.go
To make the command line tool more legible, and to improve feature parity with the Python implementation this change adds a "text" format of the style:
key: value
This format is now the default for the `criticality_score` tool as well.
Additionally, some minor doc improvements were made to cover this change and the scoring configuration.
> Add support for a text format similar to OG python implementation.

- infra/README.md
- infra/envs/staging/auth_secret_key.yaml
> Can't have underscores in kubectl secrets.

- infra/README.md
- infra/skaffold.yaml
- Cloud Deploy and skaffold want paths relative to the config.
- Unquote the value of the label so it parses correctly.
> Fix some minor bugs with the deploy config.

- cmd/collect_signals/main.go
- infra/skaffold.yaml
1. don't prune the other environment when applying the config to kubectl.
2. wait for the auth server to be ready when starting collect_signals.
> Fix some more deploy issues.

- cmd/collect_signals/Dockerfile
- cmd/collect_signals/main.go
- cmd/collect_signals/vcs.go
- cmd/collect_signals/worker.go
- cmd/criticality_score/README.md
Including the Git commit ID with each record ensures that someone can easily identify which version of the code was used to produce the given result.
> Add the Git commit ID to the data produced by the worker.

- .golangci.yml
- fixed the following lint issues:
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
> Fixed lint warning

- cmd/collect_signals/main.go
- cmd/collect_signals/worker.go
- cmd/criticality_score/README.md
- cmd/criticality_score/main.go
- infra/envs/prod/config.yaml
- infra/envs/staging/config.yaml
- internal/collector/collector.go
- internal/collector/config.go
- internal/collector/config_test.go
- internal/collector/depsdev/bq.go
- internal/collector/depsdev/dependents.go
- internal/collector/depsdev/source.go
- internal/collector/github/source.go
- internal/collector/githubmentions/source.go
- internal/collector/registry.go
- internal/collector/signal/source.go
This PR ensures the deps.dev data is always fresh.
1. Introduce "IF NOT EXISTS" to the table generation so that if more than one worker attempts to create the table none of them fail (one will create the table, the others will exit without an error)
1. Add support for dataset table expiration. This allows old/stale tables to be automatically cleaned up by GCP avoiding unlimited growth of tables.
1. Introduce a "jobID" to collection to allow for caching across sources during runs.
1. Use "jobID" in the depsdev source
- table creation is now done during `Count`
- stores a last usage cache to avoid reattempting to check if the table exists, etc
> Ensure deps.dev data is fresh for each run of Criticality Score

- internal/collector/registry.go
- The exists map is always empty so it can't contain anything.
> Fixed Bug in registry/EmptySets

- internal/scorer/algorithm/registry.go
- internal/scorer/algorithm/wam/wam.go
- internal/scorer/config.go
Removed the `GlobalRegisty` variable from `internal/scorer/algorithm/registry.go` because it isn't good practice to use global variables. I was able to remove `GlobalRegistry` because the only places any function in `registry.go` was being used was in `wam.go` and `config.go`.
The `Register()` function (From `registry.go`) was only being used in the `init()` function (From `wam.go`). The `NewALgorithm()` function (From `registry.go`) was only being used in the `Algorithm()` function (From `config.go`). Since those were the only places any function from `registry.go` was being used externaly I created a `NewRegistry()` in `Algorithm()` and then registered it, and returned `r.NewAlgorithm()`.
Because of creating a `NewRegistry()` and registering it in `Algorithm` I removed the `init()` …
> Removed GlobalRegistry from registry.go

- internal/collector/depsdev/source.go
- `DefaultDatasetName` wasn't used, so I removed it.
- I also replaced all of the `return err` with `return fmt.Errorf()` because it's considered good practice in Go to use `fmt.Errorf()` instead of just returning `err` as it provides more informative error messages. The `fmt.Errorf()` function formats a string into an error, allowing for added context and information that can aid in debugging and troubleshooting. On the other hand, returning just `err` without any extra information can make it harder to comprehend the error's cause and solution. Furthermore, using a formatted error message enhances error handling and debugging consistency.
> Refactored internal/collector/depsdev/source

- .golangci.yml
Currently, a lot of errors that are returned are just returning the error and not giving any description to what the error is when debugging (i.e. `return err`). A solution to this is to use the golang linter for wrapcheck.
- Included the wrapcheck linter
- Updated settings to ignore previous wrapcheck issues
> Included Wrapcheck linter

- .github/workflows/binary-release.yml
- .gitignore
- .goreleaser.yaml
- go.sum
Introduces goreleaser to automate the creation of binary artifacts when a new release tag is created.
Additionally uses cosign to automatically sign releases.
> Setup goreleaser to generate Go binaries.

- README.md
To solve #288, revert the change to use @main introduced in PR #320 now that we have v2.0.0 tagged.
> Switch back to @latest now that we have tagged the most recent Go code.

- .github/workflows/binary-release.yml
SLSA's GitHub Workflow can't be pinned to a commit id.
It requires the tag and a ref to work. This change fixes the workflow.
> Fix broken provenance generation - workflow must use tag.

- go.work.sum
- scripts/validate-scorecard-version.sh
Now uses the go module database to extract the origin hash, rather than trying to parse pre-release versions or query the GitHub API.
go.work.sum has been updated as well.
> Improve the scorecard version check.

- cmd/criticality_score/main.go
- cmd/criticality_score/version.go
Fixes #381.
Uses goreleaser ldflags to populate the data (see https://goreleaser.com/cookbooks/using-main.version/)
> Add a -version flag

- infra/envs/base/kustomization.yaml
- infra/envs/base/worker.yaml
- infra/envs/prod/github_auth.yaml
- infra/envs/prod/kustomization.yaml
- infra/envs/staging/github_auth.yaml
- infra/envs/staging/kustomization.yaml
- infra/envs/staging/worker_replicas.yaml
- infra/k8s/enumerate_github.yaml
- GitHub App auth used for Prod collection
- Single explicit token used for GitHub enumation (App auth doesn't work due to IP allowlisting limits)
- Removes the use of the auth server
> Update the infra to use different auth. Prod uses GH App auth.

- README.md
When the repo input is without the "https" part (only `github.com/kubernetes/kubernetes`), it throws `Repo cannot be collected` error message.
> Fix usage example url in Readme

- .dockerignore
- infra/cloudbuild/init_collect_signals/cloudbuild.yaml
- infra/images/init_collect_signals/Dockerfile
- infra/images/init_collect_signals/init.sh
Adds a simple docker image with a script for downloading and preparing the list of repositories for the `collect_signals` binary to use in "local" mode.
This image is designed to be run as an `initContainer` before the `collect_signals` binary is run.
A cloudbuild config is included so the image can be built automatically ready for GKE changes.
> Adds an init script and image for running collect_signals without GCP PubSub

- infra/images/init_collect_signals/init.sh
When a pod is restarted an `initContainer` can be run again.
The [documentation](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior) says:
> Because init containers can be restarted, retried, or re-executed, init container code should be idempotent. In particular, code that writes to files on EmptyDirs should be prepared for the possibility that an output file already exists.
This PR ensures that the collect_signals init script is idempotent so that the pod can be safely restarted.
> Ensure init is idempotent and doesn't overwrite repo list.

- internal/githubapi/errors.go
- internal/githubapi/errors_test.go
This is to help fix error handling when new errors are encountered.
> Add GitHub error type to GraphQL error messages.

- internal/collector/collector.go
- internal/collector/github/factory.go
- internal/collector/projectrepo/resolver.go
- internal/githubapi/errors.go
- internal/githubapi/errors_test.go
Handle {type: "FORBIDDEN"} GitHub GraphQL error responses that are returned when the App based authentication fails to access a repository due to GitHub org restrictions.
This change also simplifies some of the error handling, especially with multi-wrapped errors available in later versions of Go.
> Add support for FORBIDDEN GraphQL responses and simplify errors.

- cmd/collect_signals/localworker/loop.go
- go.mod
- go.sum
- go.work.sum
go-graphql-client@v0.11.0 was not wrapping and unwrapping errors correctly.
v0.12.0 fixes this issue.
Furthermore, the logging that would have made this obvious was logging at an "info" level, this change makes the log entry an "error" instead.
> Update go-graphql-client to fix error handling

- docs/CHARTER.md
This PR would replace https://github.com/ossf/criticality_score/pull/568 , adding the approved technical charter.
> Add updated charter approved by the LF Formation team

- internal/githubapi/roundtripper.go
- internal/githubapi/roundtripper_test.go
The JSON response for a 403 secondary rate limit now contains the doc_url:
https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits
This update handles this change.
> Update the secondary rate limit detector.

- cmd/collect_signals/Dockerfile
- cmd/criticality_score/Dockerfile
- cmd/csv_transfer/Dockerfile
- cmd/enumerate_github/Dockerfile
- infra/images/init_collect_signals/Dockerfile
Update the gcr.io/distroless/base:nonroot and gcr.io/google.com/cloudsdktool/google-cloud-cli:slim images to their latest tags
> Update base docker images.
